name: publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # enables npm provenance

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OS deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 pkg-config libspandsp-dev

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install (build from source)
        run: npm ci --build-from-source

      - name: Run tests
        run: npm test

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public --provenance
