name: release-manual

on:
  workflow_dispatch:
    inputs:
      release_as:
        description: 'Release as (e.g., 1.2.3). Leave blank to let Release Please decide.'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          release-as: ${{ inputs.release_as }}
